<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
      <UserSecretsId>f98e38b7-e810-421b-ae51-0920d1aab374</UserSecretsId>
  </PropertyGroup>
    
</Project>
